name: test
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: [oldstable, stable]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...
